// src/constants/students.js
export const students = [
    {
        name: 'Elève 1',
        semester: 'Semestre 2',
        promotion: 'FIE4',
        engagementType: 'Climat-Environnement',
        actionType: 'JPO',
        period: '25-27 Février 2025',
        summary: 'Formation et Animation atelier - Frésque climat',
        email: 'eleve1@example.com',
      },
      {
        name: 'Elève 2',
        semester: 'Semestre 2',
        promotion: 'FIE4',
        engagementType: 'Ecole',
        actionType: 'JPO',
        period: '25-27 Février 2025',
        summary: 'Participation Alibisup (1 demi-journée)',
        email: 'eleve2@example.com',
      },
      {
        name: 'Elève 3',
        semester: 'Semestre 2',
        promotion: 'FIE4',
        engagementType: 'Ecole',
        actionType: 'JPO',
        period: '25-27 Février 2025',
        summary: 'Organisation RDD',
        email: 'eleve3@example.com',
      },
      {
        name: 'Elève 4',
        semester: 'Semestre 2',
        promotion: 'FIE4',
        engagementType: 'Diversité',
        actionType: 'JPO',
        period: '25-27 Février 2025',
        summary: 'Tuteur Main à la pâte',
        email: 'eleve4@example.com',
      },
      {
        name: 'Elève 5',
        semester: 'Semestre 2',
        promotion: 'FIE4',
        engagementType: 'Climat-Environnement',
        actionType: 'JPO',
        period: '25-27 Février 2025',
        summary: 'Formation et Animation atelier - Frésque climat',
        email: 'eleve5@example.com',
      },
      {
        name: 'Elève 6',
        semester: 'Semestre 2',
        promotion: 'FIE4',
        engagementType: 'Ecole',
        actionType: 'JPO',
        period: '25-27 Février 2025',
        summary: 'Participation Alibisup (1 demi-journée)',
        email: 'eleve6@example.com',
      },
      {
        name: 'Elève 7',
        semester: 'Semestre 2',
        promotion: 'FIE4',
        engagementType: 'Ecole',
        actionType: 'JPO',
        period: '25-27 Février 2025',
        summary: 'Organisation RDD',
        email: 'eleve7@example.com',
      },
      {
        name: 'Elève 8',
        semester: 'Semestre 2',
        promotion: 'FIE4',
        engagementType: 'Diversité',
        actionType: 'JPO',
        period: '25-27 Février 2025',
        summary: 'Tuteur Main à la pâte',
        email: 'eleve8@example.com',
      },
      {
        name: 'Elève 9',
        semester: 'Semestre 2',
        promotion: 'FIE4',
        engagementType: 'Climat-Environnement',
        actionType: 'JPO',
        period: '25-27 Février 2025',
        summary: 'Formation et Animation atelier - Frésque climat',
        email: 'eleve9@example.com',
      },
      {
        name: 'Elève 10',
        semester: 'Semestre 2',
        promotion: 'FIE4',
        engagementType: 'Ecole',
        actionType: 'JPO',
        period: '25-27 Février 2025',
        summary: 'Participation Alibisup (1 demi-journée)',
        email: 'eleve10@example.com',
      },
    
  ];
  
  export const availablePromotions = ['FIE4', 'FIE3', 'FIE2'];